version: '3'
services:
  service1:
    build:
      context: ./microservices/services/service1
    ports:
      - '3000:3000'
    volumes:
      - ./microservices/services/service1:/app
    environment:
      NODE_ENV: development

  service2:
    build:
      context: ./microservices/services/service2
    ports:
      - '4000:4000'
    volumes:
      - ./microservices/services/service2:/app
    environment:
      NODE_ENV: development
